### ISSUE TITLE
二维码地址问题

### ISSUE THREAD

**Issue by forest21000** [BlockChainClub/qyb-wallet-clients#4]
用微信扫描二维码时，得到的地址前面有bitcon:内容，应改为qybcoin:

**Comment by let5sne** [comment]
this fixed in [https://github.com/BlockChainClub/qyb-wallet-clients/commit/df262139f43db265aef91208574c6257e4a3dc7c](url) 
请注意，编译打包之前先运行npm run postinstall ,因为涉及到对bitcore-lib核心包的修改工作量较大，故此仅在编译打包时修改源码文件
